repos:
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
      args: ["--ignore-missing-imports"]
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [python]
    - id: isort
      name: isort
      entry: isort
      language: system
      args: ["--profile", "black"]
      types: [python]
