name: Publish Packages Testpypi
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: pip install poetry

    - name: Build and Publish to PyPI
      env:
        POETRY_TESTPYPI_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi $POETRY_TESTPYPI_TOKEN
        poetry publish --build --repository testpypi
