name: Publish Packages Testpypi
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Build and Publish to Test PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
      run: |
        uv build
        uv publish --publish-url https://test.pypi.org/legacy/
