name: Python Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
          PLOT_COMPARISON_TOLERANCE: 40  # Set the tolerance for image comparison

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Choose the Python version

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra dev

    - name: Run pytest
      run: |
        uv run pytest
